### ISSUE TITLE
Missing a hackage package

### ISSUE THREAD

**Issue by mhitza** [dougalstanton/git-checklist#2]
It would be nice for it to be pushed to hackage.

**Comment by dougalstanton** [comment]
Yep, good call. I feel like I should get the file format fixed first (see #1 for details). Otherwise I have to write an upgrade tool, which isn't much fun.

**Comment by dougalstanton** [comment]
Sorted, see http://hackage.haskell.org/package/git-checklist-1.0.0.0 - hopefully my first Hackage upload actually works! :-)

**Comment by mhitza** [comment]
:thumbsup:
