### ISSUE TITLE
Incompatible dependency versions on Ubuntu 13.10

### ISSUE THREAD

**Issue by plajjan** [dougalstanton/git-checklist#6]
I'm somewhat of a Haskell newbie, so please forgive me if there's an obvious solution.

I didn't have cabal installed, so after installing it and running 'cabal configure' I'm getting error messages about failed dependencies on optparse-applicative and parsec. I try installing those using 'cabal install optparse-applicative' and the same for parsec. optparse-applicative 1.0 is installed but git-checklist depends on < 0.8, so I try to add that as a constraint on my install and instead get;

```
kll@lingloi320 ~/kod/git-checklist $ cabal configure
Resolving dependencies...
Configuring git-checklist-1.0.0.0...
Warning: This package indirectly depends on multiple versions of the same
package. This is highly likely to cause a compile failure.
package optparse-applicative-0.7.0.2 requires transformers-0.3.0.0
package mtl-2.2.1 requires transformers-0.4.1.0
```

I'm not sure how to get out of this dependency issue. Tips?
Can git-checklist be updated to support a newer version of optparse-applicative?

From the readme file this application seem quite nice, but given such a seemingly simple task it is somewhat of a threshold to have to install a Haskell build program and figure out dependencies. Why not use Python or Perl that is available on so many systems out of the box!?

**Comment by dougalstanton** [comment]
@chrisdotcode has kindly updated the dependencies for later versions of the libraries which should solve your issue. I will merge them in and update the Hackage version soon.

As for whether it's a threshold to install a Haskell build program? That doesn't seem relevant as I've already got one and know how to program it. I don't know enough Python or Perl to make a similar application. I work with the tools I've got. Cheers!

**Comment by chrisdotcode** [comment]
:thumbsup: 

Is there anything currently blocking the merge and update to Hackage?

**Comment by chrisdotcode** [comment]
Heh. This issue is pretty old, and this project seems just a tad bit dead.

@plajjan / @dougalstanton Can we close this issue so that it can be removed from my "mentions" queue? Thanks! :slightly_smiling_face:

**Comment by plajjan** [comment]
@chrisdotcode I'm fine with closing it :)

**Comment by chrisdotcode** [comment]
@plajjan Sweet! (It'll have to be from you, because I don't have access to close it)
